#!/bin/bash
set -euo pipefail
mkdir -p out

set -x
gcc -g -o out/test_c embed/test_c.c
python src/main.py patch out/test_c

g++ -g -o out/test_cpp embed/test_cpp.cpp
python src/main.py patch out/test_cpp

rustc -o out/test_rust embed/test_rust.rs
python src/main.py patch out/test_rust
