#!/bin/bash
set -euo pipefail
mkdir -p out

set -x
gcc -g -o out/test_c embed/test_c.c
python src/patch.py out/test_c

g++ -g -o out/test_cpp embed/test_cpp.cpp
python src/patch.py out/test_cpp

( cd embed/test_rust; cargo build )
cp embed/test_rust/target/debug/test_rust out
# rustc -o out/test_rust embed/test_rust.rs
python src/patch.py out/test_rust
